#ifndef CONFIG_H
#define CONFIG_H
#define PACKAGE "wayland"
#define PACKAGE_VERSION "1.24.0"
#define HAVE_SYS_PRCTL_H 1
#define HAVE_ACCEPT4 1
#define HAVE_MKOSTEMP 1
#define HAVE_POSIX_FALLOCATE 1
#define HAVE_PRCTL 1
#define HAVE_MEMFD_CREATE 1
#define HAVE_MREMAP 1
#define HAVE_STRNDUP 1
#define HAVE_BROKEN_MSG_CMSG_CLOEXEC 0
#endif
